sudo: false

language: scala

scala:
   - 2.11.8
   - 2.12.1

jdk:
   - oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

script:
  - sbt clean coverage +test coverageReport && sbt coverageAggregate

after_success:
  - sbt coveralls

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
